# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "example"

[fetch-content.libx86]
git = "https://github.com/archercreat/libx86.git"

[target.example]
type = "executable"
sources = ["src/main.cpp"]
compile-features = ["cxx_std_20"]
link-libraries = [
    "libx86"
]
