# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "libx86"

[options]
PYTHON_BINDINGS = false

[fetch-content.triton]
git = "https://github.com/JonathanSalwan/Triton.git"

[target.libx86]
type = "shared"
sources = ["src/*.cpp", "include/*.hpp"]
include-directories = ["include"]
compile-features = ["cxx_std_20"]
link-libraries = [
    "triton"
]
 